### ISSUE TITLE
goの開発環境を作成する

### ISSUE THREAD

**Issue by TomCoba** [TomCoba/learning-go#1]
goの開発環境をdockerで作成して、WEBブラウザ上から閲覧できるようにする。
参考URL：https://zenn.dev/tomi/articles/2020-10-14-go-docker

**Comment by TomCoba** [comment]
## dockerfileの作成
```
# 2020/10/14最新versionを取得
FROM golang:1.15.2-alpine
# アップデートとgitのインストール
RUN apk update && apk add git
# appディレクトリの作成
RUN mkdir /go/src/app
# ワーキングディレクトリの設定
WORKDIR /go/src/app
# ホストのファイルをコンテナの作業ディレクトリに移行
ADD . /go/src/app
```

## docker-compose.ymlの作成
```
version: "3" # composeファイルのバージョン
services:
    app: # サービス名
        build: . # ①ビルドに使うDockerfileの場所
        tty: true # ②コンテナの永続化
        volumes:
            - ./app:/go/src/app # ③マウントディレクトリ
```
